spring.datasource.url=jdbc:postgresql://localhost:5432/videoORM?useSLL=false
spring.datasource.username=ioc
spring.datasource.password=ioc
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
